### ISSUE TITLE
Testing it_IT layout

### ISSUE THREAD

**Issue by glsg79** [andischerer/atom-keyboard-localization#16]
I've installed your package to fix keybinding problems with atom.
At a glance, on Windows, it_IT layout works fine, but I noticed that you marked it as "untested".

What can I do to fully test your plugin?

I'm still learning to code and use atom so if there is a sort of procedure to make sure that all keys and special character works as they should do I would be happy to contribute.

**Comment by andischerer** [comment]
Untested just means that i've generated the keymap simply by switching my os locale. Because i'm using the german layout i can't really say if the "it_IT" keymap is fully functional on a "native" italian keyboard.
So when it is for you i remove the untested mark in the readme. Just leave me a note and thanks for your support.
