### ISSUE TITLE
neo layout ctrl right/left

### ISSUE THREAD

**Issue by ghost** [andischerer/atom-keyboard-localization#23]
using neo layout I can not use neos right/left together with ctrl (and shift) to jump/select for/backwards till word bourdary

Keys pressed (neo / qwerz representarion):
ctrl-m4-e / ctrl-altGr-f

expected:
jump right till next word bourdary

does:
open find in current buffer

key binding resolver says:
m4-e: right
ctrl-m4: ctrl-ß
ctrl-m4-e: ctrl-e

using the "normal" arrow keys works as expected — no matter if ctrl is pressed or not — and so does using arrow keys as long as ctrl is not pressed

It does not matter which m4/ctrl-key is pressed

**Comment by andischerer** [comment]
Could you try the latest release and report back if your reported wrong beavior is still there ?

**Comment by ghost** [comment]
Behavior is still the same, pressing alt gr resolves to ß (according to the keybinding resolver), which is not true, as it does not type ß. Adding ctrl and hitting any key resolves to ctrl + the key pressed and does not say anything about ß or alt gr any more…

Maybe the resolver displays it wrong…

Tested on
Ubuntu 15.04 (Gnome)
Atom 0.199.0
Keyboard Localization 1.3.1

I guess there are differences between Win and Linux as the implementation of neo layout is completely different (especially true using the non-admin-user auto hot key (ahk) tool on Win).

**Comment by groundstation1** [comment]
[ctrl + M4 + "I/E-as-arrows"] is working fine for me.

the "@" [M4 + Y] however resolves to an "&" (which already is mapped correctly to [M4 + Q], too)

In line 54 of lib\keymaps\de_DE-neo.json it should be 64 instead of 38
git-noob-change-request:
  "81": {
--        "alted": 38
++      "alted": 64
   },

my setup:
windows 8, neo-AHK drivers, german keyboard, plugin version 1.4.3

thank you so much :)

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
