### ISSUE TITLE
Ctr+/ not working with French keyboard

### ISSUE THREAD

**Issue by elalaouifaris** [andischerer/atom-keyboard-localization#80]
Hi,

I have an issue with the toggle comments command when using the French keyboard setting.
It works when the localization package is disabled.

Thank you!
Faris

**Comment by pascalchevrel** [comment]
+1

**Comment by wortelstoemp** [comment]
I had the same issue with the fr_BE layout on Windows but I fixed it by putting this in my keymap.cson file (File > Open Your Keymap):
'.platform-win32 atom-text-editor':
  'ctrl-:': 'editor:toggle-line-comments'

**Comment by pascalchevrel** [comment]
Awesome, it works, thanks :)
for Linux it's this syntax: (on one line):

```
'.platform-linux atom-text-editor': 'ctrl-:': 'editor:toggle-line-comments'
```

**Comment by gour** [comment]
Let me add that it toggle-comment does not work on my Linux machine using sl_SL keymap as well.

Disabling package and using the above-mentioned:

```
'.platform-linux atom-text-editor': 'ctrl-:': 'editor:toggle-line-comments'
```

 setting works.

**Comment by orzechow** [comment]
The command doesn't work for de_DE either. The keybinding-resolver explains why:
In order to enter a `/` on German keyboards, `shift-7` has to be pressed. So what atom receives when `ctrl-/` is pressed is 

   ctrl-shift-7

which is abviously not equal to `ctrl-/`, thus not triggering the command... 

The mentioned workaround works here too of course (but with `'ctrl-&'`).
But I'd prefer to have all the other keybindings fixed as well, without the need to map them all manually.

**Comment by nbonnotte** [comment]
I have the same issue, on a French keyboard

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
